<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Projects\abc\static\models\cafe.glb --root /models/ --keepnames --printwidth 120 --precision 2 --preload
-->

<script context="module">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  const load = () => {
    return useGltf('/models/cafe.glb')
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = load()
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Wall"
      geometry={gltf.nodes.Wall.geometry}
      material={gltf.materials.Backdrop}
      position={[1.92, 5.86, 0.18]}
    />
    <T.Group
      name="Top"
      position={[-1.58, 7.34, -1.92]}
    >
      <T.Mesh
        name="Cube011"
        geometry={gltf.nodes.Cube011.geometry}
        material={gltf.materials['Ceiling Beam']}
      />
      <T.Mesh
        name="Cube011_1"
        geometry={gltf.nodes.Cube011_1.geometry}
        material={gltf.materials['Clothes Hanger']}
      />
      <T.Mesh
        name="Cube011_2"
        geometry={gltf.nodes.Cube011_2.geometry}
        material={gltf.materials['Painting Set']}
      />
      <T.Mesh
        name="Cube011_3"
        geometry={gltf.nodes.Cube011_3.geometry}
        material={gltf.materials['Kitchen Door']}
      />
      <T.Mesh
        name="Cube011_4"
        geometry={gltf.nodes.Cube011_4.geometry}
        material={gltf.materials['Kitchen Glass']}
      />
      <T.Mesh
        name="Cube011_5"
        geometry={gltf.nodes.Cube011_5.geometry}
        material={gltf.materials['Top Wall']}
      />
      <T.Mesh
        name="Cube011_6"
        geometry={gltf.nodes.Cube011_6.geometry}
        material={gltf.materials['Dark Floor.001']}
      />
      <T.Mesh
        name="Cube011_7"
        geometry={gltf.nodes.Cube011_7.geometry}
        material={gltf.materials['Umbrella Stand']}
      />
      <T.Mesh
        name="Cube011_8"
        geometry={gltf.nodes.Cube011_8.geometry}
        material={gltf.materials['Umbrella Plastic']}
      />
      <T.Mesh
        name="Cube011_9"
        geometry={gltf.nodes.Cube011_9.geometry}
        material={gltf.materials['Umbrella Wood']}
      />
      <T.Mesh
        name="Cube011_10"
        geometry={gltf.nodes.Cube011_10.geometry}
        material={gltf.materials['Umbrella Metal']}
      />
      <T.Group
        name="Eight"
        position={[0.02, -1.99, -1.68]}
      >
        <T.Mesh
          name="Cube031"
          geometry={gltf.nodes.Cube031.geometry}
          material={gltf.materials.Menu}
        />
        <T.Mesh
          name="Cube031_1"
          geometry={gltf.nodes.Cube031_1.geometry}
          material={gltf.materials['Menu Hanger']}
        />
        <T.Mesh
          name="Cube031_2"
          geometry={gltf.nodes.Cube031_2.geometry}
          material={gltf.materials['Photo Frame']}
        />
        <T.Mesh
          name="Cube031_3"
          geometry={gltf.nodes.Cube031_3.geometry}
          material={gltf.materials['Photo Content']}
        />
        <T.Mesh
          name="Cube031_4"
          geometry={gltf.nodes.Cube031_4.geometry}
          material={gltf.materials['Clip Wood']}
        />
        <T.Mesh
          name="Cube031_5"
          geometry={gltf.nodes.Cube031_5.geometry}
          material={gltf.materials['Clip Metal']}
        />
        <T.Mesh
          name="Cube031_6"
          geometry={gltf.nodes.Cube031_6.geometry}
          material={gltf.materials['Picture Frame']}
        />
        <T.Mesh
          name="Cube031_7"
          geometry={gltf.nodes.Cube031_7.geometry}
          material={gltf.materials['Grid Frame']}
        />
      </T.Group>
      <T.Group
        name="Nine"
        position={[-0.68, -4.13, 1.12]}
      >
        <T.Mesh
          name="Cube032"
          geometry={gltf.nodes.Cube032.geometry}
          material={gltf.materials['Welcome Mat.001']}
        />
        <T.Mesh
          name="Cube032_1"
          geometry={gltf.nodes.Cube032_1.geometry}
          material={gltf.materials['Railing Metal.001']}
        />
        <T.Mesh
          name="Cube032_2"
          geometry={gltf.nodes.Cube032_2.geometry}
          material={gltf.materials['Red Couch']}
        />
        <T.Mesh
          name="Cube032_3"
          geometry={gltf.nodes.Cube032_3.geometry}
          material={gltf.materials['Round Table']}
        />
        <T.Mesh
          name="Cube032_4"
          geometry={gltf.nodes.Cube032_4.geometry}
          material={gltf.materials['Round Table Bot']}
        />
        <T.Mesh
          name="Cube032_5"
          geometry={gltf.nodes.Cube032_5.geometry}
          material={gltf.materials['Red Chair']}
        />
        <T.Mesh
          name="Cube032_6"
          geometry={gltf.nodes.Cube032_6.geometry}
          material={gltf.materials['Red Chair Bot']}
        />
        <T.Mesh
          name="Cube032_7"
          geometry={gltf.nodes.Cube032_7.geometry}
          material={gltf.materials['Social Sign']}
        />
        <T.Mesh
          name="Cube032_8"
          geometry={gltf.nodes.Cube032_8.geometry}
          material={gltf.materials['Sign Holder']}
        />
      </T.Group>
      <T.Group
        name="Six"
        position={[-0.68, -4.13, 1.12]}
      >
        <T.Mesh
          name="Cube033"
          geometry={gltf.nodes.Cube033.geometry}
          material={gltf.materials['Dark Floor']}
        />
        <T.Mesh
          name="Cube033_1"
          geometry={gltf.nodes.Cube033_1.geometry}
          material={gltf.materials['Light Floor']}
        />
        <T.Mesh
          name="Cube033_2"
          geometry={gltf.nodes.Cube033_2.geometry}
          material={gltf.materials.CounterTop}
        />
        <T.Mesh
          name="Cube033_3"
          geometry={gltf.nodes.Cube033_3.geometry}
          material={gltf.materials['Counter.001']}
        />
        <T.Mesh
          name="Cube033_4"
          geometry={gltf.nodes.Cube033_4.geometry}
          material={gltf.materials['Front Countertop']}
        />
        <T.Mesh
          name="Cube033_5"
          geometry={gltf.nodes.Cube033_5.geometry}
          material={gltf.materials['Stone Counter']}
        />
        <T.Mesh
          name="Cube033_6"
          geometry={gltf.nodes.Cube033_6.geometry}
          material={gltf.materials['Bottom Counter']}
        />
      </T.Group>
      <T.Group
        name="Ten"
        position={[-0.68, -4.13, 1.12]}
      >
        <T.Mesh
          name="Cube035"
          geometry={gltf.nodes.Cube035.geometry}
          material={gltf.materials['Light Metal Counter']}
        />
        <T.Mesh
          name="Cube035_1"
          geometry={gltf.nodes.Cube035_1.geometry}
          material={gltf.materials['Dark Metal.001']}
        />
        <T.Mesh
          name="Cube035_2"
          geometry={gltf.nodes.Cube035_2.geometry}
          material={gltf.materials['Grey Plastic.001']}
        />
        <T.Mesh
          name="Cube035_3"
          geometry={gltf.nodes.Cube035_3.geometry}
          material={gltf.materials['Tamping Mat.001']}
        />
        <T.Mesh
          name="Cube035_4"
          geometry={gltf.nodes.Cube035_4.geometry}
          material={gltf.materials['Smooth Wood.001']}
        />
        <T.Mesh
          name="Cube035_5"
          geometry={gltf.nodes.Cube035_5.geometry}
          material={gltf.materials['Metal.001']}
        />
        <T.Mesh
          name="Cube035_6"
          geometry={gltf.nodes.Cube035_6.geometry}
          material={gltf.materials['Smooth Plastic.001']}
        />
        <T.Mesh
          name="Cube035_7"
          geometry={gltf.nodes.Cube035_7.geometry}
          material={gltf.materials['Ceiling Beam.001']}
        />
        <T.Mesh
          name="Cube035_8"
          geometry={gltf.nodes.Cube035_8.geometry}
          material={gltf.materials['White Metal.001']}
        />
        <T.Mesh
          name="Cube035_9"
          geometry={gltf.nodes.Cube035_9.geometry}
          material={gltf.materials['Dish Frame.001']}
        />
        <T.Mesh
          name="Cube035_10"
          geometry={gltf.nodes.Cube035_10.geometry}
          material={gltf.materials['Plate.001']}
        />
        <T.Mesh
          name="Cube035_11"
          geometry={gltf.nodes.Cube035_11.geometry}
          material={gltf.materials['Hard Plastic.001']}
        />
        <T.Mesh
          name="Cube035_12"
          geometry={gltf.nodes.Cube035_12.geometry}
          material={gltf.materials['Sponge.001']}
        />
        <T.Mesh
          name="Cube035_13"
          geometry={gltf.nodes.Cube035_13.geometry}
          material={gltf.materials['Material.002']}
        />
        <T.Mesh
          name="Cube035_14"
          geometry={gltf.nodes.Cube035_14.geometry}
          material={gltf.materials['Sign Holder.001']}
        />
        <T.Mesh
          name="Cube035_15"
          geometry={gltf.nodes.Cube035_15.geometry}
          material={gltf.materials['Front Sink']}
        />
        <T.Mesh
          name="Cube035_16"
          geometry={gltf.nodes.Cube035_16.geometry}
          material={gltf.materials['Front Grating']}
        />
        <T.Mesh
          name="Cube035_17"
          geometry={gltf.nodes.Cube035_17.geometry}
          material={gltf.materials['Smooth Plastic']}
        />
        <T.Mesh
          name="Cube035_18"
          geometry={gltf.nodes.Cube035_18.geometry}
          material={gltf.materials['Smooth Wood']}
        />
        <T.Mesh
          name="Cube035_19"
          geometry={gltf.nodes.Cube035_19.geometry}
          material={gltf.materials.Book}
        />
        <T.Mesh
          name="Cube035_20"
          geometry={gltf.nodes.Cube035_20.geometry}
          material={gltf.materials.Pages}
        />
        <T.Mesh
          name="Cube035_21"
          geometry={gltf.nodes.Cube035_21.geometry}
          material={gltf.materials.Pot}
        />
        <T.Mesh
          name="Cube035_22"
          geometry={gltf.nodes.Cube035_22.geometry}
          material={gltf.materials.Soil}
        />
        <T.Mesh
          name="Cube035_23"
          geometry={gltf.nodes.Cube035_23.geometry}
          material={gltf.materials.Leaf}
        />
        <T.Mesh
          name="Cube035_24"
          geometry={gltf.nodes.Cube035_24.geometry}
          material={gltf.materials.Stem}
        />
        <T.Mesh
          name="Cube035_25"
          geometry={gltf.nodes.Cube035_25.geometry}
          material={gltf.materials['Tip Box']}
        />
        <T.Mesh
          name="Cube035_26"
          geometry={gltf.nodes.Cube035_26.geometry}
          material={gltf.materials['Hard Plastic']}
        />
        <T.Mesh
          name="Cube035_27"
          geometry={gltf.nodes.Cube035_27.geometry}
          material={gltf.materials['Smooth Plastic.002']}
        />
        <T.Mesh
          name="Cube035_28"
          geometry={gltf.nodes.Cube035_28.geometry}
          material={gltf.materials['Cashier Plastic']}
        />
        <T.Mesh
          name="Cube035_29"
          geometry={gltf.nodes.Cube035_29.geometry}
          material={gltf.materials['Hard Plastic.002']}
        />
        <T.Mesh
          name="Cube035_30"
          geometry={gltf.nodes.Cube035_30.geometry}
          material={gltf.materials['Light Grey Plastic']}
        />
        <T.Mesh
          name="Cube035_31"
          geometry={gltf.nodes.Cube035_31.geometry}
          material={gltf.materials['Glazed Glass']}
        />
        <T.Mesh
          name="Cube035_32"
          geometry={gltf.nodes.Cube035_32.geometry}
          material={gltf.materials['White Metal']}
        />
        <T.Mesh
          name="Cube035_33"
          geometry={gltf.nodes.Cube035_33.geometry}
          material={gltf.materials.Numpad}
        />
        <T.Mesh
          name="Cube035_34"
          geometry={gltf.nodes.Cube035_34.geometry}
          material={gltf.materials['Card Pad']}
        />
        <T.Mesh
          name="Cube035_35"
          geometry={gltf.nodes.Cube035_35.geometry}
          material={gltf.materials['Terminal Screen']}
        />
        <T.Mesh
          name="Cube035_36"
          geometry={gltf.nodes.Cube035_36.geometry}
          material={gltf.materials['Receipt Tray']}
        />
        <T.Mesh
          name="Cube035_37"
          geometry={gltf.nodes.Cube035_37.geometry}
          material={gltf.materials['Pastry Display']}
        />
        <T.Mesh
          name="Cube035_38"
          geometry={gltf.nodes.Cube035_38.geometry}
          material={gltf.materials['Counter Glass']}
        />
      </T.Group>
    </T.Group>
    <T.Group
      name="Bottom"
      position={[2.15, 1.47, -2.77]}
      scale={0.9}
    >
      <T.Mesh
        name="Cube013"
        geometry={gltf.nodes.Cube013.geometry}
        material={gltf.materials['Condiment Station Top']}
      />
      <T.Mesh
        name="Cube013_1"
        geometry={gltf.nodes.Cube013_1.geometry}
        material={gltf.materials['Condiment Station Bot']}
      />
      <T.Mesh
        name="Cube013_2"
        geometry={gltf.nodes.Cube013_2.geometry}
        material={gltf.materials['Condiment Props']}
      />
      <T.Mesh
        name="Cube013_3"
        geometry={gltf.nodes.Cube013_3.geometry}
        material={gltf.materials['Fairy String']}
      />
      <T.Mesh
        name="Cube013_4"
        geometry={gltf.nodes.Cube013_4.geometry}
        material={gltf.materials['Fairy Light']}
      />
      <T.Mesh
        name="Cube013_5"
        geometry={gltf.nodes.Cube013_5.geometry}
        material={gltf.materials['Fairy Glass']}
      />
      <T.Mesh
        name="Cube013_6"
        geometry={gltf.nodes.Cube013_6.geometry}
        material={gltf.materials['Clock Metal']}
      />
      <T.Mesh
        name="Cube013_7"
        geometry={gltf.nodes.Cube013_7.geometry}
        material={gltf.materials.Clock}
      />
      <T.Mesh
        name="Cube013_8"
        geometry={gltf.nodes.Cube013_8.geometry}
        material={gltf.materials['Bottom Wall.001']}
      />
      <T.Mesh
        name="Cube013_9"
        geometry={gltf.nodes.Cube013_9.geometry}
        material={gltf.materials['Stencil Floor.001']}
      />
      <T.Mesh
        name="Cube013_10"
        geometry={gltf.nodes.Cube013_10.geometry}
        material={gltf.materials['Sides Bottom.001']}
      />
      <T.Mesh
        name="Cube013_11"
        geometry={gltf.nodes.Cube013_11.geometry}
        material={gltf.materials['Toilet Door.001']}
      />
      <T.Group
        name="Four"
        position={[0.55, -2.48, 3.75]}
        rotation={[0, -1.57, 0]}
        scale={1.12}
      >
        <T.Mesh
          name="Cube041"
          geometry={gltf.nodes.Cube041.geometry}
          material={gltf.materials.SeatTop}
        />
        <T.Mesh
          name="Cube041_1"
          geometry={gltf.nodes.Cube041_1.geometry}
          material={gltf.materials.SeatBot}
        />
        <T.Mesh
          name="Cube041_2"
          geometry={gltf.nodes.Cube041_2.geometry}
          material={gltf.materials.RoundTop}
        />
        <T.Mesh
          name="Cube041_3"
          geometry={gltf.nodes.Cube041_3.geometry}
          material={gltf.materials.RoundBot}
        />
        <T.Mesh
          name="Cube041_4"
          geometry={gltf.nodes.Cube041_4.geometry}
          material={gltf.materials.PairTableTop}
        />
        <T.Mesh
          name="Cube041_5"
          geometry={gltf.nodes.Cube041_5.geometry}
          material={gltf.materials.PairTableBot}
        />
      </T.Group>
      <T.Group
        name="Seven"
        position={[-4.99, -0.71, 1.64]}
      >
        <T.Mesh
          name="Cube045"
          geometry={gltf.nodes.Cube045.geometry}
          material={gltf.materials.Sideboard}
        />
        <T.Mesh
          name="Cube045_1"
          geometry={gltf.nodes.Cube045_1.geometry}
          material={gltf.materials['Stair Glass']}
        />
        <T.Mesh
          name="Cube045_2"
          geometry={gltf.nodes.Cube045_2.geometry}
          material={gltf.materials['Lego Group']}
        />
        <T.Mesh
          name="Cube045_3"
          geometry={gltf.nodes.Cube045_3.geometry}
          material={gltf.materials['Emissive Blue']}
        />
        <T.Mesh
          name="Cube045_4"
          geometry={gltf.nodes.Cube045_4.geometry}
          material={gltf.materials['Emissive Orange']}
        />
        <T.Mesh
          name="Cube045_5"
          geometry={gltf.nodes.Cube045_5.geometry}
          material={gltf.materials.Steps}
        />
        <T.Mesh
          name="Cube045_6"
          geometry={gltf.nodes.Cube045_6.geometry}
          material={gltf.materials['Railing Metal']}
        />
      </T.Group>
      <T.Group
        name="Two"
        position={[-3.35, -2.31, 3.86]}
        scale={1.12}
      >
        <T.Mesh
          name="Cube048"
          geometry={gltf.nodes.Cube048.geometry}
          material={gltf.materials['Bag Holder']}
        />
        <T.Mesh
          name="Cube048_1"
          geometry={gltf.nodes.Cube048_1.geometry}
          material={gltf.materials.HighTop}
        />
        <T.Mesh
          name="Cube048_2"
          geometry={gltf.nodes.Cube048_2.geometry}
          material={gltf.materials.HighBot}
        />
        <T.Mesh
          name="Cube048_3"
          geometry={gltf.nodes.Cube048_3.geometry}
          material={gltf.materials.LongTop}
        />
        <T.Mesh
          name="Cube048_4"
          geometry={gltf.nodes.Cube048_4.geometry}
          material={gltf.materials.LongBot}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
