<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Projects\abc\static\models\cafe_backup.glb --root /models/ --keepnames --printwidth 120 --precision 2 --preload
-->

<script context="module">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  const load = () => {
    return useGltf('/models/cafe_backup.glb')
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = load()
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="Bottom"
      position={[1.62, -0.35, 1.56]}
    >
      <T.Mesh
        name="Cube013"
        geometry={gltf.nodes.Cube013.geometry}
        material={gltf.materials['Bottom Wall']}
      />
      <T.Mesh
        name="Cube013_1"
        geometry={gltf.nodes.Cube013_1.geometry}
        material={gltf.materials['Stencil Floor']}
      />
      <T.Mesh
        name="Cube013_2"
        geometry={gltf.nodes.Cube013_2.geometry}
        material={gltf.materials['Sides Bottom']}
      />
      <T.Mesh
        name="Cube013_3"
        geometry={gltf.nodes.Cube013_3.geometry}
        material={gltf.materials.SeatTop}
      />
      <T.Mesh
        name="Cube013_4"
        geometry={gltf.nodes.Cube013_4.geometry}
        material={gltf.materials.SeatBot}
      />
      <T.Mesh
        name="Cube013_5"
        geometry={gltf.nodes.Cube013_5.geometry}
        material={gltf.materials.RoundTop}
      />
      <T.Mesh
        name="Cube013_6"
        geometry={gltf.nodes.Cube013_6.geometry}
        material={gltf.materials.RoundBot}
      />
      <T.Mesh
        name="Cube013_7"
        geometry={gltf.nodes.Cube013_7.geometry}
        material={gltf.materials.PairTableTop}
      />
      <T.Mesh
        name="Cube013_8"
        geometry={gltf.nodes.Cube013_8.geometry}
        material={gltf.materials.PairTableBot}
      />
      <T.Mesh
        name="Cube013_9"
        geometry={gltf.nodes.Cube013_9.geometry}
        material={gltf.materials['Table Sign']}
      />
      <T.Mesh
        name="Cube013_10"
        geometry={gltf.nodes.Cube013_10.geometry}
        material={gltf.materials['Flag Holder']}
      />
      <T.Mesh
        name="Cube013_11"
        geometry={gltf.nodes.Cube013_11.geometry}
        material={gltf.materials['Lego Group']}
      />
      <T.Mesh
        name="Cube013_12"
        geometry={gltf.nodes.Cube013_12.geometry}
        material={gltf.materials['Emissive Blue']}
      />
      <T.Mesh
        name="Cube013_13"
        geometry={gltf.nodes.Cube013_13.geometry}
        material={gltf.materials['Emissive Orange']}
      />
      <T.Mesh
        name="Cube013_14"
        geometry={gltf.nodes.Cube013_14.geometry}
        material={gltf.materials.Sideboard}
      />
      <T.Mesh
        name="Cube013_15"
        geometry={gltf.nodes.Cube013_15.geometry}
        material={gltf.materials['Stair Glass']}
      />
      <T.Mesh
        name="Cube013_16"
        geometry={gltf.nodes.Cube013_16.geometry}
        material={gltf.materials.Steps}
      />
      <T.Mesh
        name="Cube013_17"
        geometry={gltf.nodes.Cube013_17.geometry}
        material={gltf.materials['Bag Holder']}
      />
      <T.Mesh
        name="Cube013_18"
        geometry={gltf.nodes.Cube013_18.geometry}
        material={gltf.materials['Toilet Door']}
      />
      <T.Mesh
        name="Cube013_19"
        geometry={gltf.nodes.Cube013_19.geometry}
        material={gltf.materials['Condiment Station Top']}
      />
      <T.Mesh
        name="Cube013_20"
        geometry={gltf.nodes.Cube013_20.geometry}
        material={gltf.materials['Condiment Station Bot']}
      />
      <T.Mesh
        name="Cube013_21"
        geometry={gltf.nodes.Cube013_21.geometry}
        material={gltf.materials['Railing Metal']}
      />
      <T.Mesh
        name="Cube013_22"
        geometry={gltf.nodes.Cube013_22.geometry}
        material={gltf.materials.HighTop}
      />
      <T.Mesh
        name="Cube013_23"
        geometry={gltf.nodes.Cube013_23.geometry}
        material={gltf.materials.HighBot}
      />
      <T.Mesh
        name="Cube013_24"
        geometry={gltf.nodes.Cube013_24.geometry}
        material={gltf.materials.LongTop}
      />
      <T.Mesh
        name="Cube013_25"
        geometry={gltf.nodes.Cube013_25.geometry}
        material={gltf.materials.LongBot}
      />
      <T.Mesh
        name="Cube013_26"
        geometry={gltf.nodes.Cube013_26.geometry}
        material={gltf.materials['Condiment Props']}
      />
      <T.Mesh
        name="Cube013_27"
        geometry={gltf.nodes.Cube013_27.geometry}
        material={gltf.materials['Fairy String']}
      />
      <T.Mesh
        name="Cube013_28"
        geometry={gltf.nodes.Cube013_28.geometry}
        material={gltf.materials['Fairy Light']}
      />
      <T.Mesh
        name="Cube013_29"
        geometry={gltf.nodes.Cube013_29.geometry}
        material={gltf.materials['Fairy Glass']}
      />
      <T.Mesh
        name="Cube013_30"
        geometry={gltf.nodes.Cube013_30.geometry}
        material={gltf.materials['Clock Metal']}
      />
      <T.Mesh
        name="Cube013_31"
        geometry={gltf.nodes.Cube013_31.geometry}
        material={gltf.materials.Clock}
      />
      <T.Mesh
        name="Cube013_32"
        geometry={gltf.nodes.Cube013_32.geometry}
        material={gltf.materials['Serving Tray']}
      />
    </T.Group>
    <T.Group
      name="Top"
      position={[-1.14, 4.13, -1.14]}
    >
      <T.Mesh
        name="Cube002"
        geometry={gltf.nodes.Cube002.geometry}
        material={gltf.materials['Ceiling Beam']}
      />
      <T.Mesh
        name="Cube002_1"
        geometry={gltf.nodes.Cube002_1.geometry}
        material={gltf.materials['Clothes Hanger']}
      />
      <T.Mesh
        name="Cube002_2"
        geometry={gltf.nodes.Cube002_2.geometry}
        material={gltf.materials['Painting Set']}
      />
      <T.Mesh
        name="Cube002_3"
        geometry={gltf.nodes.Cube002_3.geometry}
        material={gltf.materials['Kitchen Door']}
      />
      <T.Mesh
        name="Cube002_4"
        geometry={gltf.nodes.Cube002_4.geometry}
        material={gltf.materials['Kitchen Glass']}
      />
      <T.Mesh
        name="Cube002_5"
        geometry={gltf.nodes.Cube002_5.geometry}
        material={gltf.materials['Top Wall']}
      />
      <T.Mesh
        name="Cube002_6"
        geometry={gltf.nodes.Cube002_6.geometry}
        material={gltf.materials['Dark Floor.001']}
      />
      <T.Mesh
        name="Cube002_7"
        geometry={gltf.nodes.Cube002_7.geometry}
        material={gltf.materials['Light Floor']}
      />
      <T.Mesh
        name="Cube002_8"
        geometry={gltf.nodes.Cube002_8.geometry}
        material={gltf.materials['Welcome Mat']}
      />
      <T.Mesh
        name="Cube002_9"
        geometry={gltf.nodes.Cube002_9.geometry}
        material={gltf.materials.Menu}
      />
      <T.Mesh
        name="Cube002_10"
        geometry={gltf.nodes.Cube002_10.geometry}
        material={gltf.materials['Menu Hanger']}
      />
      <T.Mesh
        name="Cube002_11"
        geometry={gltf.nodes.Cube002_11.geometry}
        material={gltf.materials.CounterTop}
      />
      <T.Mesh
        name="Cube002_12"
        geometry={gltf.nodes.Cube002_12.geometry}
        material={gltf.materials['Counter.001']}
      />
      <T.Mesh
        name="Cube002_13"
        geometry={gltf.nodes.Cube002_13.geometry}
        material={gltf.materials['Light Metal Counter']}
      />
      <T.Mesh
        name="Cube002_14"
        geometry={gltf.nodes.Cube002_14.geometry}
        material={gltf.materials['Dark Metal.001']}
      />
      <T.Mesh
        name="Cube002_15"
        geometry={gltf.nodes.Cube002_15.geometry}
        material={gltf.materials['Grey Plastic.001']}
      />
      <T.Mesh
        name="Cube002_16"
        geometry={gltf.nodes.Cube002_16.geometry}
        material={gltf.materials['Tamping Mat.001']}
      />
      <T.Mesh
        name="Cube002_17"
        geometry={gltf.nodes.Cube002_17.geometry}
        material={gltf.materials['Smooth Wood.001']}
      />
      <T.Mesh
        name="Cube002_18"
        geometry={gltf.nodes.Cube002_18.geometry}
        material={gltf.materials['Metal.001']}
      />
      <T.Mesh
        name="Cube002_19"
        geometry={gltf.nodes.Cube002_19.geometry}
        material={gltf.materials['Smooth Plastic.001']}
      />
      <T.Mesh
        name="Cube002_20"
        geometry={gltf.nodes.Cube002_20.geometry}
        material={gltf.materials['Ceiling Beam.001']}
      />
      <T.Mesh
        name="Cube002_21"
        geometry={gltf.nodes.Cube002_21.geometry}
        material={gltf.materials['White Metal.001']}
      />
      <T.Mesh
        name="Cube002_22"
        geometry={gltf.nodes.Cube002_22.geometry}
        material={gltf.materials['Dish Frame.001']}
      />
      <T.Mesh
        name="Cube002_23"
        geometry={gltf.nodes.Cube002_23.geometry}
        material={gltf.materials['Plate.001']}
      />
      <T.Mesh
        name="Cube002_24"
        geometry={gltf.nodes.Cube002_24.geometry}
        material={gltf.materials['Hard Plastic.001']}
      />
      <T.Mesh
        name="Cube002_25"
        geometry={gltf.nodes.Cube002_25.geometry}
        material={gltf.materials['Sponge.001']}
      />
      <T.Mesh
        name="Cube002_26"
        geometry={gltf.nodes.Cube002_26.geometry}
        material={gltf.materials['Material.002']}
      />
      <T.Mesh
        name="Cube002_27"
        geometry={gltf.nodes.Cube002_27.geometry}
        material={gltf.materials['Sign Holder.001']}
      />
      <T.Mesh
        name="Cube002_28"
        geometry={gltf.nodes.Cube002_28.geometry}
        material={gltf.materials['Front Countertop']}
      />
      <T.Mesh
        name="Cube002_29"
        geometry={gltf.nodes.Cube002_29.geometry}
        material={gltf.materials['Stone Counter']}
      />
      <T.Mesh
        name="Cube002_30"
        geometry={gltf.nodes.Cube002_30.geometry}
        material={gltf.materials['Bottom Counter']}
      />
      <T.Mesh
        name="Cube002_31"
        geometry={gltf.nodes.Cube002_31.geometry}
        material={gltf.materials['Front Sink']}
      />
      <T.Mesh
        name="Cube002_32"
        geometry={gltf.nodes.Cube002_32.geometry}
        material={gltf.materials['Front Grating']}
      />
      <T.Mesh
        name="Cube002_33"
        geometry={gltf.nodes.Cube002_33.geometry}
        material={gltf.materials['Smooth Plastic']}
      />
      <T.Mesh
        name="Cube002_34"
        geometry={gltf.nodes.Cube002_34.geometry}
        material={gltf.materials['Smooth Wood']}
      />
      <T.Mesh
        name="Cube002_35"
        geometry={gltf.nodes.Cube002_35.geometry}
        material={gltf.materials.Book}
      />
      <T.Mesh
        name="Cube002_36"
        geometry={gltf.nodes.Cube002_36.geometry}
        material={gltf.materials.Pages}
      />
      <T.Mesh
        name="Cube002_37"
        geometry={gltf.nodes.Cube002_37.geometry}
        material={gltf.materials.Pot}
      />
      <T.Mesh
        name="Cube002_38"
        geometry={gltf.nodes.Cube002_38.geometry}
        material={gltf.materials.Soil}
      />
      <T.Mesh
        name="Cube002_39"
        geometry={gltf.nodes.Cube002_39.geometry}
        material={gltf.materials.Leaf}
      />
      <T.Mesh
        name="Cube002_40"
        geometry={gltf.nodes.Cube002_40.geometry}
        material={gltf.materials.Stem}
      />
      <T.Mesh
        name="Cube002_41"
        geometry={gltf.nodes.Cube002_41.geometry}
        material={gltf.materials['Tip Box']}
      />
      <T.Mesh
        name="Cube002_42"
        geometry={gltf.nodes.Cube002_42.geometry}
        material={gltf.materials['Hard Plastic']}
      />
      <T.Mesh
        name="Cube002_43"
        geometry={gltf.nodes.Cube002_43.geometry}
        material={gltf.materials['Smooth Plastic.002']}
      />
      <T.Mesh
        name="Cube002_44"
        geometry={gltf.nodes.Cube002_44.geometry}
        material={gltf.materials['Cashier Plastic']}
      />
      <T.Mesh
        name="Cube002_45"
        geometry={gltf.nodes.Cube002_45.geometry}
        material={gltf.materials['Hard Plastic.002']}
      />
      <T.Mesh
        name="Cube002_46"
        geometry={gltf.nodes.Cube002_46.geometry}
        material={gltf.materials['Light Grey Plastic']}
      />
      <T.Mesh
        name="Cube002_47"
        geometry={gltf.nodes.Cube002_47.geometry}
        material={gltf.materials['Glazed Glass']}
      />
      <T.Mesh
        name="Cube002_48"
        geometry={gltf.nodes.Cube002_48.geometry}
        material={gltf.materials['White Metal']}
      />
      <T.Mesh
        name="Cube002_49"
        geometry={gltf.nodes.Cube002_49.geometry}
        material={gltf.materials.Numpad}
      />
      <T.Mesh
        name="Cube002_50"
        geometry={gltf.nodes.Cube002_50.geometry}
        material={gltf.materials['Card Pad']}
      />
      <T.Mesh
        name="Cube002_51"
        geometry={gltf.nodes.Cube002_51.geometry}
        material={gltf.materials['Terminal Screen']}
      />
      <T.Mesh
        name="Cube002_52"
        geometry={gltf.nodes.Cube002_52.geometry}
        material={gltf.materials['Receipt Tray']}
      />
      <T.Mesh
        name="Cube002_53"
        geometry={gltf.nodes.Cube002_53.geometry}
        material={gltf.materials['Pastry Display']}
      />
      <T.Mesh
        name="Cube002_54"
        geometry={gltf.nodes.Cube002_54.geometry}
        material={gltf.materials['Counter Glass']}
      />
      <T.Mesh
        name="Cube002_55"
        geometry={gltf.nodes.Cube002_55.geometry}
        material={gltf.materials['Umbrella Stand']}
      />
      <T.Mesh
        name="Cube002_56"
        geometry={gltf.nodes.Cube002_56.geometry}
        material={gltf.materials['Umbrella Plastic']}
      />
      <T.Mesh
        name="Cube002_57"
        geometry={gltf.nodes.Cube002_57.geometry}
        material={gltf.materials['Umbrella Wood']}
      />
      <T.Mesh
        name="Cube002_58"
        geometry={gltf.nodes.Cube002_58.geometry}
        material={gltf.materials['Umbrella Metal']}
      />
      <T.Mesh
        name="Cube002_59"
        geometry={gltf.nodes.Cube002_59.geometry}
        material={gltf.materials['Dark Floor']}
      />
      <T.Mesh
        name="Cube002_60"
        geometry={gltf.nodes.Cube002_60.geometry}
        material={gltf.materials['Railing Metal.001']}
      />
      <T.Mesh
        name="Cube002_61"
        geometry={gltf.nodes.Cube002_61.geometry}
        material={gltf.materials['Red Couch']}
      />
      <T.Mesh
        name="Cube002_62"
        geometry={gltf.nodes.Cube002_62.geometry}
        material={gltf.materials['Round Table']}
      />
      <T.Mesh
        name="Cube002_63"
        geometry={gltf.nodes.Cube002_63.geometry}
        material={gltf.materials['Round Table Bot']}
      />
      <T.Mesh
        name="Cube002_64"
        geometry={gltf.nodes.Cube002_64.geometry}
        material={gltf.materials['Red Chair']}
      />
      <T.Mesh
        name="Cube002_65"
        geometry={gltf.nodes.Cube002_65.geometry}
        material={gltf.materials['Red Chair Bot']}
      />
      <T.Mesh
        name="Cube002_66"
        geometry={gltf.nodes.Cube002_66.geometry}
        material={gltf.materials['Social Sign']}
      />
      <T.Mesh
        name="Cube002_67"
        geometry={gltf.nodes.Cube002_67.geometry}
        material={gltf.materials['Sign Holder']}
      />
      <T.Mesh
        name="Cube002_68"
        geometry={gltf.nodes.Cube002_68.geometry}
        material={gltf.materials['Photo Frame']}
      />
      <T.Mesh
        name="Cube002_69"
        geometry={gltf.nodes.Cube002_69.geometry}
        material={gltf.materials['Photo Content']}
      />
      <T.Mesh
        name="Cube002_70"
        geometry={gltf.nodes.Cube002_70.geometry}
        material={gltf.materials['Clip Wood']}
      />
      <T.Mesh
        name="Cube002_71"
        geometry={gltf.nodes.Cube002_71.geometry}
        material={gltf.materials['Clip Metal']}
      />
      <T.Mesh
        name="Cube002_72"
        geometry={gltf.nodes.Cube002_72.geometry}
        material={gltf.materials['Picture Frame']}
      />
      <T.Mesh
        name="Cube002_73"
        geometry={gltf.nodes.Cube002_73.geometry}
        material={gltf.materials['Grid Frame']}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
