<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Projects\abc\static\models\cafe.glb --root /models/ --keepnames --printwidth 120 --precision 2 --draco true --preload --transform --resolution 4096
-->

<script module>
  import { T, useTask } from "@threlte/core";
  import { useGltf, useDraco, Instance, InstancedMesh, useCursor } from "@threlte/extras";
  import { Sheet, SheetObject, Sequence } from "@threlte/theatre";

  const load = () => {
    return useGltf("/models/cafe.glb", { dracoLoader: useDraco() });
  };

  export const preload = async () => {
    await load();
  };
</script>

<script>
  let { fallback, error, children, ref = $bindable(), ...props } = $props();
  import { CircleGeometry, TextureLoader, ClampToEdgeWrapping, LinearFilter } from "three";
  import { onMount } from "svelte";
  import { Tween } from "svelte/motion";
  import { cubicInOut, linear } from "svelte/easing";
  import { getScene } from "$lib/stores/worldState.svelte.js";
  const scene = getScene();

  const gltf = load();

  const nullZone = -999;
  const hideZone = (t, condition) => {
    return condition ? nullZone : t;
  };

  const cafeTopFull = 7.34;
  const cafeTopHalf = 2.71;
  const cafeBotFull = 1.47;

  let bearVisible = $state(true);
  const bearKeyframe = 125;
  let bearScale = new Tween([1, 1, 1], {
    duration: bearKeyframe,
    easing: cubicInOut,
  });

  let bearRotation = new Tween([0, 0, 0], {
    duration: bearKeyframe,
    easing: cubicInOut,
  });

  let bearYDelta = new Tween(0, {
    duration: bearKeyframe,
    easing: cubicInOut,
  });

  async function playTada() {
    await Promise.all([
      bearScale.set([0.9, 0.9, 0.9]),
      bearRotation.set([0, 0, (-3 * Math.PI) / 180]),
      bearYDelta.set(0.05),
    ]);
    await Promise.all([
      bearScale.set([1.2, 1.2, 1.2]),
      bearRotation.set([0, 0, (3 * Math.PI) / 180]),
      bearYDelta.set(0.1),
    ]);
    await Promise.all([
      bearScale.set([1.2, 1.2, 1.2]),
      bearRotation.set([0, 0, (-3 * Math.PI) / 180]),
    ]);
    await Promise.all([
      bearScale.set([1.2, 1.2, 1.2]),
      bearRotation.set([0, 0, (3 * Math.PI) / 180]),
    ]);
    await Promise.all([bearScale.set([1, 1, 1]), bearRotation.set([0, 0, 0]), bearYDelta.set(0)]);
  }

  let cafeTopY = $derived.by(() => {
    if (scene.currentState.currentFloor === 0) {
      return cafeTopFull;
    } else if (scene.currentState.currentFloor === 1) {
      return cafeTopHalf;
    } else {
      return nullZone;
    }
  });

  let cafeBottomY = $derived.by(() => {
    if (scene.currentState.currentFloor === 0) {
      return cafeBotFull;
    } else if (scene.currentState.currentFloor === 1) {
      return nullZone;
    } else {
      return cafeBotFull;
    }
  });

  let robotPOVController = $state(null);
  const rotationTween = new Tween(0, {
    duration: 2000,
    easing: linear,
  });

  function loopRotation() {
    const nextRotation = rotationTween.current + Math.PI * 2;
    rotationTween.set(nextRotation).then(loopRotation);
  }

  loopRotation();

  const plateKeyframe = 650;
  let plateLocation = new Tween([0, 0, 0], {
    duration: plateKeyframe,
    easing: cubicInOut,
  });

  const consumeDessert = (e) => {
    e.stopPropagation();
    plateLocation.set([1, 0.18, 0.14]).then(() => {
      setTimeout(() => {
        scene.currentState.currentPlate = "empty";
        plateLocation.set([0, 0, 0.0]);
      }, scene.eatTime);
    });
    scene.setOverlay("eat");
  };

  const { hovering } = useCursor("grab");
  let faceTextures = $state([]);
  let currentFaceRoam = $state(4);
  let nextFaceRoam = $state(4);
  let roamingAlpha = new Tween(1, {
    duration: 450,
    easing: linear,
  });

  function changeRoam(index) {
    if (index === currentFaceRoam) return;

    nextFaceRoam = index;
    roamingAlpha.set(0).then(() => {
      currentFaceRoam = index;
      roamingAlpha.set(1, { duration: 0 });
    });
  }

  let currentFacePOV = $state(0);
  let nextFacePOV = $state(0);
  let transitionAlpha = new Tween(1, {
    duration: 300,
    easing: linear,
  });

  function changeFace(index) {
    nextFacePOV = index;
    transitionAlpha.set(0).then(() => {
      currentFacePOV = index;
      transitionAlpha.set(1, { duration: 0 });
    });
  }

  onMount(() => {
    const loader = new TextureLoader();
    faceTextures = Array.from({ length: 10 }, (_, i) => {
      const tex = loader.load(`/textures/cat-face/face-${i}.webp`);
      tex.colorSpace = "srgb";
      tex.flipY = false;
      tex.wrapS = tex.wrapT = ClampToEdgeWrapping;
      tex.minFilter = LinearFilter;
      tex.magFilter = LinearFilter;

      return tex;
    });
  });

  let cooldownActive = $state(false);
  let faceResetTimeout = $state(null);
  let timer = 0;

  const faceWeights = [40, 15, 15, 10, 10, 2, 25, 15, 25, 15];
  function weightedRandom(weights) {
    const total = weights.reduce((a, b) => a + b, 0);
    let r = Math.random() * total;
    for (let i = 0; i < weights.length; i++) {
      if (r < weights[i]) return i;
      r -= weights[i];
    }
    return weights.length - 1;
  }

  useTask((delta) => {
    timer += delta;
    if (timer >= 5) {
      const weight = scene.currentState.plateCount > 4 ? faceWeights : faceWeights.slice(0, 6);
      let newFaceRoam = weightedRandom(weight);

      changeRoam(newFaceRoam);
      timer = 0;
    }
  });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Wall"
      geometry={gltf.nodes.Wall.geometry}
      material={gltf.materials.Backdrop}
      position={[4.25, 5.89, 11.56]}
    />
    <T.Group name="Bottom" position={[2.15, cafeBottomY, -2.77]}>
      <T.Group
        name="Dish"
        position={scene.currentState.povCamera
          ? plateLocation.current
          : [nullZone, nullZone, nullZone]}
        visible={scene.currentState.povCamera}
      >
        {#if scene.currentState.currentPlate != ""}
          <T.Mesh
            name="Order_Plate"
            geometry={gltf.nodes.Order_Plate.geometry}
            material={gltf.materials["Showcase Plate.001"]}
            position={[2.3, -1.64, 3.48]}
          />
        {/if}
        <T.Group
          name="Dish Collection"
          position={[2.33, -1.57, 3.47]}
          onclick={(e) => {
            consumeDessert(e);
          }}
        >
          {#if scene.currentState.currentPlate === "cheesecake"}
            <T.Mesh
              name="Chesecake"
              geometry={gltf.nodes.Chesecake.geometry}
              material={gltf.materials["Cheesecake Main"]}
              position={[0, 0, 0]}
            />
          {/if}
          {#if scene.currentState.currentPlate === "earlgrey-cheesecake"}
            <T.Mesh
              name="Basque_Cheesecake"
              geometry={gltf.nodes.Basque_Cheesecake.geometry}
              material={gltf.materials["Basque Cheesecake"]}
              position={[-0.025, 0, 0.025]}
            />{/if}
          {#if scene.currentState.currentPlate === "brownie-cheesecake"}
            <T.Group name="Brownie_Basque" position={[0.04, -0.03, 0.015]}>
              <T.Mesh
                name="Cube091"
                geometry={gltf.nodes.Cube091.geometry}
                material={gltf.materials["Brownie Basque"]}
              />
              <T.Mesh
                name="Cube091_1"
                geometry={gltf.nodes.Cube091_1.geometry}
                material={gltf.materials["Brownie Basque Top"]}
              />
            </T.Group>{/if}
          {#if scene.currentState.currentPlate === "choc-cremebrulee"}
            <T.Group name="Choc_Ramekin" position={[0.01, -0.01, 0.02]}>
              <T.Mesh
                name="Cylinder010"
                geometry={gltf.nodes.Cylinder010.geometry}
                material={gltf.materials["Ramekin.001"]}
              />
              <T.Mesh
                name="Cylinder010_1"
                geometry={gltf.nodes.Cylinder010_1.geometry}
                material={gltf.materials["Choc Creme Brulee"]}
              />
            </T.Group>{/if}
          {#if scene.currentState.currentPlate === "financier"}
            <T.Mesh
              name="Financier"
              geometry={gltf.nodes.Financier.geometry}
              material={gltf.materials["Financier.001"]}
              position={[0.0, -0.04, 0.0]}
            />{/if}
          {#if scene.currentState.currentPlate === "lava-cake"}
            <T.Group name="Lava_Cake" position={[-0.01, -0.02, 0.01]}>
              <T.Mesh
                name="Cylinder027"
                geometry={gltf.nodes.Cylinder027.geometry}
                material={gltf.materials["Lava Cake"]}
              />
              <T.Mesh
                name="Cylinder027_1"
                geometry={gltf.nodes.Cylinder027_1.geometry}
                material={gltf.materials["Lava Chocoalte"]}
              />
            </T.Group>{/if}
          {#if scene.currentState.currentPlate === "matcha-cake"}
            <T.Group name="Matcha_Cake" position={[-0.01, -0.02, 0.01]}>
              <T.Mesh
                name="Cylinder002"
                geometry={gltf.nodes.Cylinder002.geometry}
                material={gltf.materials["Matcha Cake"]}
              />
              <T.Mesh
                name="Cylinder002_1"
                geometry={gltf.nodes.Cylinder002_1.geometry}
                material={gltf.materials["Matcha Chocolate"]}
              />
            </T.Group>{/if}
          {#if scene.currentState.currentPlate === "matcha-muffin"}
            <T.Group name="Muffin" position={[0.01, -0.035, 0.02]}>
              <T.Mesh
                name="Cylinder026"
                geometry={gltf.nodes.Cylinder026.geometry}
                material={gltf.materials["Muffin Cup"]}
              />
              <T.Mesh
                name="Cylinder026_1"
                geometry={gltf.nodes.Cylinder026_1.geometry}
                material={gltf.materials["Muffin Top"]}
              />
            </T.Group>
          {/if}
          {#if scene.currentState.currentPlate === "cremebrulee"}
            <T.Group name="Ramekin" position={[0.01, -0.01, 0.02]}>
              <T.Mesh
                name="Cylinder012"
                geometry={gltf.nodes.Cylinder012.geometry}
                material={gltf.materials["Ramekin.001"]}
              />
              <T.Mesh
                name="Cylinder012_1"
                geometry={gltf.nodes.Cylinder012_1.geometry}
                material={gltf.materials["Creme Brulee"]}
              />
            </T.Group>
          {/if}
        </T.Group>
      </T.Group>
      <T.Mesh
        name="Cube013"
        geometry={gltf.nodes.Cube013.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_1"
        geometry={gltf.nodes.Cube013_1.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_2"
        geometry={gltf.nodes.Cube013_2.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_3"
        geometry={gltf.nodes.Cube013_3.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_4"
        geometry={gltf.nodes.Cube013_4.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_5"
        geometry={gltf.nodes.Cube013_5.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_6"
        geometry={gltf.nodes.Cube013_6.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_7"
        geometry={gltf.nodes.Cube013_7.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_8"
        geometry={gltf.nodes.Cube013_8.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_9"
        geometry={gltf.nodes.Cube013_9.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_10"
        geometry={gltf.nodes.Cube013_10.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <T.Mesh
        name="Cube013_11"
        geometry={gltf.nodes.Cube013_11.geometry}
        material={gltf.materials["Toilet Door.001"]}
      />
      <Sheet name="Robot-Roam">
        <Sequence
          iterationCount={Infinity}
          autoplay
          delay={1000}
          rate={Math.max(0.25, 1 - scene.currentState.plateCount * 0.04) * 1.25}
        >
          <SheetObject key="Cat Base">
            {#snippet children({ Transform })}
              <Transform>
                <T.Group
                  name="Cat_Base_Roam"
                  rotation={[0, 0, 0]}
                  visible={scene.currentState.interactables.flag && !scene.currentState.povCamera}
                >
                  <InstancedMesh position={[0, 0.35, 0]} frustumCulled={false}>
                    <T.BufferGeometry is={gltf.nodes.Order_Plate.geometry} />
                    <T.MeshStandardMaterial is={gltf.materials["Showcase Plate.001"]} />

                    {#each Array(scene.currentState.plateCount) as _, i}
                      <Instance position={[0, i * 0.04, 0]} />
                    {/each}
                  </InstancedMesh>
                  <T.Mesh
                    name="Cat_Base"
                    geometry={gltf.nodes.Cat_Base.geometry}
                    material={gltf.materials["Robot Texure"]}
                    position={[0.64, -1.9, 6.18]}
                  />
                  <SheetObject key="Cat Face Roam">
                    {#snippet children({ Transform })}
                      <Transform>
                        <T.Group name="Cat_Face_Roam" position={[0, 0.63, 0]}>
                          <T.Mesh
                            name="Sphere"
                            geometry={gltf.nodes.Sphere.geometry}
                            material={gltf.materials["Robot Texure"]}
                          />
                          <T.Mesh name="Sphere_2_Front" geometry={gltf.nodes.Sphere_1.geometry}>
                            <T.MeshBasicMaterial
                              transparent={true}
                              opacity={1 - roamingAlpha.current}
                              map={faceTextures[nextFaceRoam]}
                            />
                          </T.Mesh>
                          <T.Mesh name="Sphere_2_Back" geometry={gltf.nodes.Sphere_1.geometry}>
                            <T.MeshBasicMaterial
                              transparent={true}
                              opacity={roamingAlpha.current}
                              map={faceTextures[currentFaceRoam]}
                            />
                          </T.Mesh>
                        </T.Group>
                      </Transform>
                    {/snippet}
                  </SheetObject>
                  <T.Mesh
                    name="FakeShadow"
                    geometry={new CircleGeometry(0.39, 32)}
                    rotation={[-Math.PI / 2, 0, 0]}
                    position={[0, -0.685, 0]}
                  >
                    <T.MeshBasicMaterial transparent={true} opacity={0.25} color="black" />
                  </T.Mesh>
                </T.Group>
              </Transform>
            {/snippet}
          </SheetObject>
        </Sequence>
      </Sheet>
      <Sheet name="Robot-POV">
        <Sequence autoplay={false} bind:this={robotPOVController}>
          <SheetObject key="POV Base">
            {#snippet children({ Transform })}
              <Transform>
                <T.Group
                  name="Cat_Base_POV"
                  rotation={[0, 0, 0]}
                  visible={scene.currentState.povCamera}
                >
                  <T.Mesh
                    name="Cat_Base"
                    geometry={gltf.nodes.Cat_Base.geometry}
                    material={gltf.materials["Robot Texure"]}
                    position={[0.64, -1.9, 6.18]}
                  />
                  <T.Mesh
                    name="Tablet"
                    geometry={gltf.nodes.Tablet.geometry}
                    material={gltf.materials.Misc}
                    position={[0, hideZone(0.34 + 0.1, !scene.currentState.povCamera), 0.01]}
                    rotation={[0, rotationTween.current, -0.5]}
                    onclick={(e) => {
                      e.stopPropagation();
                      scene.setOverlay("flag");
                    }}
                  />
                  <SheetObject key="POV Face">
                    {#snippet children({ Transform })}
                      <Transform>
                        <T.Group
                          name="Cat_Face_POV"
                          onpointerenter={() => ($hovering = true)}
                          onpointerleave={() => ($hovering = false)}
                          position.y={hideZone(0.63, !scene.currentState.povCamera)}
                          onclick={(e) => {
                            e.stopPropagation();
                            if (cooldownActive) return;

                            let newFace = 1 + Math.floor(Math.random() * 4);
                            while (newFace === currentFacePOV) {
                              newFace = 1 + Math.floor(Math.random() * 4);
                            }

                            changeFace(newFace);

                            clearTimeout(faceResetTimeout);
                            faceResetTimeout = setTimeout(
                              () => {
                                changeFace(0);
                                cooldownActive = false;
                              },
                              1000 + Math.floor(Math.random() * 2000),
                            );
                            cooldownActive = true;
                          }}
                        >
                          <T.Mesh
                            name="Sphere"
                            geometry={gltf.nodes.Sphere.geometry}
                            material={gltf.materials["Robot Texure"]}
                          />
                          <T.Mesh name="Sphere_2_Front" geometry={gltf.nodes.Sphere_1.geometry}>
                            <T.MeshBasicMaterial
                              transparent={true}
                              opacity={1 - transitionAlpha.current}
                              map={faceTextures[nextFacePOV]}
                            />
                          </T.Mesh>
                          <T.Mesh name="Sphere_2_Back" geometry={gltf.nodes.Sphere_1.geometry}>
                            <T.MeshBasicMaterial
                              transparent={true}
                              opacity={transitionAlpha.current}
                              map={faceTextures[currentFacePOV]}
                            />
                          </T.Mesh>
                        </T.Group>
                      </Transform>
                    {/snippet}
                  </SheetObject>
                </T.Group>
              </Transform>
            {/snippet}
          </SheetObject>
        </Sequence>
      </Sheet>
      <T.Group
        name="Flag"
        position={[2.09, hideZone(-1.46, scene.currentState.povCamera), 3.44]}
        visible={!scene.currentState.povCamera}
        onclick={(e) => {
          e.stopPropagation();
          scene.togglePOVCamera();
          if (!scene.currentState.interactables.flag) {
            robotPOVController.position = 0;
            robotPOVController.play();
          }
        }}
      >
        <T.Mesh
          name="Cube012"
          geometry={gltf.nodes.Cube012.geometry}
          material={gltf.materials["Table Sign"]}
        />
        <T.Mesh
          name="Cube012_1"
          geometry={gltf.nodes.Cube012_1.geometry}
          material={gltf.materials["Flag Holder"]}
        />
        <T.Mesh
          name="Flag_Hitbox"
          geometry={gltf.nodes.Flag_Hitbox.geometry}
          material={gltf.nodes.Flag_Hitbox.material}
          onclick={(e) => {
            e.stopPropagation();
            scene.togglePOVCamera();
            if (!scene.currentState.interactables.flag) {
              robotPOVController.position = 0;
              robotPOVController.play();
            }
          }}
        >
          <T.MeshBasicMaterial transparent opacity={0} depthWrite={false} />
        </T.Mesh>
      </T.Group>
      <T.Group name="Four" position={[0.49, -2.22, 3.36]}>
        <T.Mesh
          name="Cube041"
          geometry={gltf.nodes.Cube041.geometry}
          material={gltf.materials.SeatTop}
        />
        <T.Mesh
          name="Cube041_1"
          geometry={gltf.nodes.Cube041_1.geometry}
          material={gltf.materials.SeatTop}
        />
        <T.Mesh
          name="Cube041_2"
          geometry={gltf.nodes.Cube041_2.geometry}
          material={gltf.materials.SeatTop}
        />
        <T.Mesh
          name="Cube041_3"
          geometry={gltf.nodes.Cube041_3.geometry}
          material={gltf.materials.SeatTop}
        />
        <T.Mesh
          name="Cube041_4"
          geometry={gltf.nodes.Cube041_4.geometry}
          material={gltf.materials.SeatTop}
        />
        <T.Mesh
          name="Cube041_5"
          geometry={gltf.nodes.Cube041_5.geometry}
          material={gltf.materials.SeatTop}
        />
      </T.Group>
      <T.Group name="Seven" position={[-4.48, -0.64, 1.47]}>
        <T.Mesh
          name="Cube045"
          geometry={gltf.nodes.Cube045.geometry}
          material={gltf.materials["Lego Group"]}
        />
        <T.Mesh
          name="Cube045_1"
          geometry={gltf.nodes.Cube045_1.geometry}
          material={gltf.materials["Stair Glass"]}
        />
        <T.Mesh
          name="Cube045_2"
          geometry={gltf.nodes.Cube045_2.geometry}
          material={gltf.materials["Lego Group"]}
        />
        <T.Mesh
          name="Cube045_3"
          geometry={gltf.nodes.Cube045_3.geometry}
          material={gltf.materials["Lego Group"]}
        />
        <T.Mesh
          name="Earl_Street"
          geometry={gltf.nodes.Earl_Street.geometry}
          material={gltf.materials["Lego Group"]}
          onclick={(e) => {
            e.stopPropagation();
            scene.toggleHud();
          }}
        />
      </T.Group>
      <T.Mesh
        name="Toilet-F"
        geometry={gltf.nodes["Toilet-F"].geometry}
        material={gltf.materials["Toilet Door.001"]}
        position={[-1.49, -1.37, -0.83]}
        onclick={(e) => {
          e.stopPropagation();
          scene.setFToilet();
        }}
      />
      <T.Mesh
        name="Toilet-M"
        geometry={gltf.nodes["Toilet-M"].geometry}
        material={gltf.materials["Toilet Door.001"]}
        position={[0.03, -1.37, -0.83]}
        onclick={(e) => {
          e.stopPropagation();
          if (scene.currentState.interactables.fToilet) {
            scene.setMToilet();
          } else {
            scene.openDialog("men");
          }
        }}
      />
      <T.Group name="Two" position={[-3, -2.07, 3.46]}>
        <T.Mesh
          name="Cube048"
          geometry={gltf.nodes.Cube048.geometry}
          material={gltf.materials["Bag Holder"]}
        />
        <T.Mesh
          name="Cube048_1"
          geometry={gltf.nodes.Cube048_1.geometry}
          material={gltf.materials["Bag Holder"]}
        />
        <T.Mesh
          name="Cube048_2"
          geometry={gltf.nodes.Cube048_2.geometry}
          material={gltf.materials["Bag Holder"]}
        />
        <T.Mesh
          name="Cube048_3"
          geometry={gltf.nodes.Cube048_3.geometry}
          material={gltf.materials["Bag Holder"]}
        />
        <T.Mesh
          name="Cube048_4"
          geometry={gltf.nodes.Cube048_4.geometry}
          material={gltf.materials["Bag Holder"]}
        />
      </T.Group>
    </T.Group>
    <T.Group name="Top" position={[-1.58, cafeTopY, -1.92]}>
      <T.Mesh
        name="Cube011"
        geometry={gltf.nodes.Cube011.geometry}
        material={gltf.materials["Painting Set"]}
      />
      <T.Mesh
        name="Cube011_1"
        geometry={gltf.nodes.Cube011_1.geometry}
        material={gltf.materials["Painting Set"]}
      />
      <T.Mesh
        name="Cube011_2"
        geometry={gltf.nodes.Cube011_2.geometry}
        material={gltf.materials["Painting Set"]}
      />
      <T.Mesh
        name="Cube011_3"
        geometry={gltf.nodes.Cube011_3.geometry}
        material={gltf.materials["Painting Set"]}
      />
      <T.Mesh
        name="Cube011_4"
        geometry={gltf.nodes.Cube011_4.geometry}
        material={gltf.materials["Painting Set"]}
      />
      <T.Mesh
        name="Cube011_5"
        geometry={gltf.nodes.Cube011_5.geometry}
        material={gltf.materials["Painting Set"]}
      />
      <T.Mesh
        name="Cube011_6"
        geometry={gltf.nodes.Cube011_6.geometry}
        material={gltf.materials["Painting Set"]}
      />
      <T.Mesh
        name="Cube011_7"
        geometry={gltf.nodes.Cube011_7.geometry}
        material={gltf.materials["Painting Set"]}
      />
      <T.Mesh
        name="Cube011_8"
        geometry={gltf.nodes.Cube011_8.geometry}
        material={gltf.materials["Painting Set"]}
      />
      <T.Mesh
        name="Cube011_9"
        geometry={gltf.nodes.Cube011_9.geometry}
        material={gltf.materials["Painting Set"]}
      />
      {#if scene.currentState.interactables.bear}
        <T.Group
          name="Bear"
          position={[4.98, bearVisible ? -2.86 + bearYDelta.current : nullZone, 3.78]}
          visible={bearVisible}
          scale={bearScale.current}
          rotation={bearRotation.current}
          onclick={(e) => {
            e.stopPropagation();
            const res = scene.touchBear();
            if (res === true) {
              scene.setOverlay("bear");
              setTimeout(() => {
                bearVisible = false;
              }, 2000);
            } else if (res === false) {
              playTada();
            }
          }}
        >
          <T.Mesh
            name="Sphere002"
            geometry={gltf.nodes.Sphere002.geometry}
            material={gltf.materials.fabric_pink}
          />
          <T.Mesh
            name="Sphere002_1"
            geometry={gltf.nodes.Sphere002_1.geometry}
            material={gltf.materials.fabric_pink}
          />
          <T.Mesh
            name="Sphere002_2"
            geometry={gltf.nodes.Sphere002_2.geometry}
            material={gltf.materials.fabric_pink}
          />
          <T.Mesh
            name="Sphere002_3"
            geometry={gltf.nodes.Sphere002_3.geometry}
            material={gltf.materials.fabric_pink}
          />
          <T.Mesh
            name="Sphere002_4"
            geometry={gltf.nodes.Sphere002_4.geometry}
            material={gltf.materials.fabric_pink}
          />
          <T.Mesh
            name="Sphere002_5"
            geometry={gltf.nodes.Sphere002_5.geometry}
            material={gltf.materials.fabric_pink}
          />
          <T.Mesh
            name="Sphere002_6"
            geometry={gltf.nodes.Sphere002_6.geometry}
            material={gltf.materials.fabric_pink}
          />
        </T.Group>
        <T.Mesh
          name="Disturb"
          geometry={gltf.nodes.Disturb.geometry}
          material={gltf.materials.Disturb}
          position={[5.4, -3.02, 3.42]}
        />
      {/if}
      <T.Group
        name="Cashier_Screen"
        position={[4.12, -2.77, 0.75]}
        onclick={(e) => {
          e.stopPropagation();
          scene.setOverlay("payment");
        }}
      >
        <T.Mesh
          name="Cube098"
          geometry={gltf.nodes.Cube098.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube098_1"
          geometry={gltf.nodes.Cube098_1.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
      </T.Group>
      <T.Group name="Eight" position={[0.02, -1.99, -1.68]}>
        <T.Mesh
          name="Cube031"
          geometry={gltf.nodes.Cube031.geometry}
          material={gltf.materials["Photo Frame"]}
        />
        <T.Mesh
          name="Cube031_1"
          geometry={gltf.nodes.Cube031_1.geometry}
          material={gltf.materials["Photo Frame"]}
        />
        <T.Mesh
          name="Photo_Grid"
          geometry={gltf.nodes.Photo_Grid.geometry}
          material={gltf.materials["Photo Frame"]}
          position={[-0.12, -0.12, -0.04]}
        >
          <T.Mesh
            name="Photo_Hitbox"
            geometry={gltf.nodes.Photo_Hitbox.geometry}
            position={[0, -0.04, 0]}
            rotation={[0, 0, Math.PI]}
            scale={[-1.19, -0.9, -0.08]}
            onclick={(e) => {
              e.stopPropagation();
              scene.setOverlay("grid");
            }}
          >
            <T.MeshBasicMaterial transparent opacity={0} depthWrite={false} />
          </T.Mesh>
          <T.Mesh
            name="Photo_Frame_1"
            geometry={gltf.nodes.Photo_Frame_1.geometry}
            material={gltf.materials["Photo Frame"]}
          />
          <T.Mesh
            name="Photo_Frame_2"
            geometry={gltf.nodes.Photo_Frame_2.geometry}
            material={gltf.materials["Photo Frame"]}
          />
          <T.Mesh
            name="Photo_Frame_3"
            geometry={gltf.nodes.Photo_Frame_3.geometry}
            material={gltf.materials["Photo Frame"]}
          />
          <T.Mesh
            name="Photo_Frame_4"
            geometry={gltf.nodes.Photo_Frame_4.geometry}
            material={gltf.materials["Photo Frame"]}
          />
        </T.Mesh>
      </T.Group>
      <T.Group name="Eleven" position={[5.83, -2.86, -1.43]}>
        <T.Mesh
          name="Cube014"
          geometry={gltf.nodes.Cube014.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_1"
          geometry={gltf.nodes.Cube014_1.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_2"
          geometry={gltf.nodes.Cube014_2.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_3"
          geometry={gltf.nodes.Cube014_3.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_4"
          geometry={gltf.nodes.Cube014_4.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_5"
          geometry={gltf.nodes.Cube014_5.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_6"
          geometry={gltf.nodes.Cube014_6.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_7"
          geometry={gltf.nodes.Cube014_7.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_8"
          geometry={gltf.nodes.Cube014_8.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_9"
          geometry={gltf.nodes.Cube014_9.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_10"
          geometry={gltf.nodes.Cube014_10.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_11"
          geometry={gltf.nodes.Cube014_11.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
        <T.Mesh
          name="Cube014_12"
          geometry={gltf.nodes.Cube014_12.geometry}
          material={gltf.materials["Light Metal Counter"]}
        />
      </T.Group>
      <T.Group name="Nine" position={[-0.68, -4.13, 1.12]}>
        <T.Mesh
          name="Cube032"
          geometry={gltf.nodes.Cube032.geometry}
          material={gltf.materials["Social Sign"]}
        />
        <T.Mesh
          name="Cube032_1"
          geometry={gltf.nodes.Cube032_1.geometry}
          material={gltf.materials["Social Sign"]}
        />
        <T.Mesh
          name="Cube032_2"
          geometry={gltf.nodes.Cube032_2.geometry}
          material={gltf.materials["Social Sign"]}
        />
        <T.Mesh
          name="Cube032_3"
          geometry={gltf.nodes.Cube032_3.geometry}
          material={gltf.materials["Social Sign"]}
        />
        <T.Mesh
          name="Cube032_4"
          geometry={gltf.nodes.Cube032_4.geometry}
          material={gltf.materials["Social Sign"]}
        />
        <T.Mesh
          name="Cube032_5"
          geometry={gltf.nodes.Cube032_5.geometry}
          material={gltf.materials["Social Sign"]}
        />
        <T.Mesh
          name="Cube032_6"
          geometry={gltf.nodes.Cube032_6.geometry}
          material={gltf.materials["Social Sign"]}
        />
        <T.Mesh
          name="Cube032_7"
          geometry={gltf.nodes.Cube032_7.geometry}
          material={gltf.materials["Social Sign"]}
        />
        <T.Mesh
          name="Cube032_8"
          geometry={gltf.nodes.Cube032_8.geometry}
          material={gltf.materials["Social Sign"]}
        />
        {#if !scene.currentState.interactables.bear}
          <T.Group name="Social_Sign" position={[5.78, 1.18, 2.57]}>
            <T.Mesh
              name="Cube039"
              geometry={gltf.nodes.Cube039.geometry}
              material={gltf.materials["Social Sign"]}
            />
            <T.Mesh
              name="Cube039_1"
              geometry={gltf.nodes.Cube039_1.geometry}
              material={gltf.materials["Social Sign"]}
            />
          </T.Group>
        {/if}
      </T.Group>
      <T.Mesh
        name="Painting_Set"
        geometry={gltf.nodes.Painting_Set.geometry}
        material={gltf.materials["Painting Set"]}
        position={[-1.73, -2.13, 0.39]}
        onclick={(e) => {
          e.stopPropagation();
          scene.setOverlay("photo");
        }}
      />
      <T.Group name="Six" position={[-0.68, -4.13, 1.12]}>
        <T.Mesh
          name="Cube033"
          geometry={gltf.nodes.Cube033.geometry}
          material={gltf.materials["Dark Floor"]}
          onclick={(e) => {
            e.stopPropagation();
          }}
        />
        <T.Mesh
          name="Cube033_1"
          geometry={gltf.nodes.Cube033_1.geometry}
          material={gltf.materials["Dark Floor"]}
        />
        <T.Mesh
          name="Cube033_2"
          geometry={gltf.nodes.Cube033_2.geometry}
          material={gltf.materials["Dark Floor"]}
        />
        <T.Mesh
          name="Cube033_3"
          geometry={gltf.nodes.Cube033_3.geometry}
          material={gltf.materials["Dark Floor"]}
        />
        <T.Mesh
          name="Cube033_4"
          geometry={gltf.nodes.Cube033_4.geometry}
          material={gltf.materials["Dark Floor"]}
        />
        <T.Mesh
          name="Cube033_5"
          geometry={gltf.nodes.Cube033_5.geometry}
          material={gltf.materials["Dark Floor"]}
        />
        <T.Mesh
          name="Cube033_6"
          geometry={gltf.nodes.Cube033_6.geometry}
          material={gltf.materials["Dark Floor"]}
        />
      </T.Group>
      <T.Group name="Ten" position={[4.12, -2.77, 0.75]}>
        <T.Mesh
          name="Cube035"
          geometry={gltf.nodes.Cube035.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_1"
          geometry={gltf.nodes.Cube035_1.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_2"
          geometry={gltf.nodes.Cube035_2.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_3"
          geometry={gltf.nodes.Cube035_3.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_4"
          geometry={gltf.nodes.Cube035_4.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_5"
          geometry={gltf.nodes.Cube035_5.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_6"
          geometry={gltf.nodes.Cube035_6.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_7"
          geometry={gltf.nodes.Cube035_7.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_8"
          geometry={gltf.nodes.Cube035_8.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_9"
          geometry={gltf.nodes.Cube035_9.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_10"
          geometry={gltf.nodes.Cube035_10.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_11"
          geometry={gltf.nodes.Cube035_11.geometry}
          material={gltf.materials["Glazed Glass"]}
        />
        <T.Mesh
          name="Cube035_12"
          geometry={gltf.nodes.Cube035_12.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_13"
          geometry={gltf.nodes.Cube035_13.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_14"
          geometry={gltf.nodes.Cube035_14.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_15"
          geometry={gltf.nodes.Cube035_15.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_16"
          geometry={gltf.nodes.Cube035_16.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_17"
          geometry={gltf.nodes.Cube035_17.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Cube035_18"
          geometry={gltf.nodes.Cube035_18.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
      </T.Group>
      <T.Group name="Twelve" position={[1.27, -2.64, 0.69]}>
        <T.Mesh
          name="Cube036"
          geometry={gltf.nodes.Cube036.geometry}
          material={gltf.materials.Book}
        />
        <T.Mesh
          name="Cube036_1"
          geometry={gltf.nodes.Cube036_1.geometry}
          material={gltf.materials.Book}
        />
        <T.Mesh
          name="Cube036_2"
          geometry={gltf.nodes.Cube036_2.geometry}
          material={gltf.materials.Book}
        />
        <T.Mesh
          name="Cube036_3"
          geometry={gltf.nodes.Cube036_3.geometry}
          material={gltf.materials.Book}
        />
        <T.Mesh
          name="Cube036_4"
          geometry={gltf.nodes.Cube036_4.geometry}
          material={gltf.materials.Book}
        />
        <T.Mesh
          name="Cube036_5"
          geometry={gltf.nodes.Cube036_5.geometry}
          material={gltf.materials.Book}
        />
        <T.Mesh
          name="Cube036_6"
          geometry={gltf.nodes.Cube036_6.geometry}
          material={gltf.materials.Book}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
