<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 cat-transformed.glb --root /models/transformed/ --keepnames --printwidth 120 --precision 2 --draco true --preload
-->

<script context="module">
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  const load = () => {
    return useGltf('/models/transformed/cat-transformed.glb')
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = load()

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Main">
      <T.Group
        name="UnityArmature"
        position={[1.16, 0.65, -0.23]}
        rotation={[0.05, 0.01, -0.01]}
        scale={0.91}
      >
        <T is={gltf.nodes.hips} />
        <T is={gltf.nodes.driver} />
        <T.SkinnedMesh
          name="CAFE_ARC"
          geometry={gltf.nodes.CAFE_ARC.geometry}
          material={gltf.materials.Quest}
          skeleton={gltf.nodes.CAFE_ARC.skeleton}
          morphTargetDictionary={gltf.nodes.CAFE_ARC.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.CAFE_ARC.morphTargetInfluences}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
