<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Projects\abc\static\models\cat.glb --root /models/ --keepnames --printwidth 120 --precision 2 --draco true --preload --transform --resolution 4096
-->

<script context="module">
  import { T } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  const load = () => {
    return useGltf("/models/cat-transformed.glb", { dracoLoader: useDraco() });
  };

  export const preload = async () => {
    await load();
  };
</script>

<script>
  let { fallback, error, children, ref = $bindable(), ...props } = $props();

  const gltf = load();
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Cat_Base"
      geometry={gltf.nodes.Cat_Base.geometry}
      material={gltf.materials["Cashier Plastic"]}
      position={[0, -2.4, 0]}
    >
      <T.Group name="Cat_Cylinder" position={[-0.02, 1.7, 0]}>
        <T.Mesh
          name="Reference002"
          geometry={gltf.nodes.Reference002.geometry}
          material={gltf.materials["Hard Plastic"]}
        />
        <T.Mesh
          name="Reference002_1"
          geometry={gltf.nodes.Reference002_1.geometry}
          material={gltf.materials["Cashier Plastic"]}
        />
        <T.Mesh
          name="Reference002_2"
          geometry={gltf.nodes.Reference002_2.geometry}
          material={gltf.materials["White Metal"]}
        />
        <T.Group
          name="Face"
          position={[0, 1.27, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.05}
        >
          <T.Mesh
            name="Sphere"
            geometry={gltf.nodes.Sphere.geometry}
            material={gltf.materials["Hard Plastic"]}
          />
          <T.Mesh
            name="Sphere_1"
            geometry={gltf.nodes.Sphere_1.geometry}
            material={gltf.materials["Light Plastic"]}
          />
          <T.Mesh
            name="Sphere_2"
            geometry={gltf.nodes.Sphere_2.geometry}
            material={gltf.materials.Face}
          />
        </T.Group>
      </T.Group>
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
