<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 earl-street-ktx-transformed.glb --root /models/transformed/ --keepnames --printwidth 120 --precision 2 --draco true --preload
-->

<script context="module">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  const load = () => {
    return useGltf('/models/transformed/earl-street-ktx-transformed.glb')
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = load()
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Earl_Street"
      geometry={gltf.nodes.Earl_Street.geometry}
      material={gltf.materials.Seven}
      position={[-2.32, 0.83, -1.3]}
    >
      <T.Mesh
        name="Earl_Street_Shell"
        geometry={gltf.nodes.Earl_Street_Shell.geometry}
        material={gltf.materials['Lego Shell']}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
