<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Projects\abc\static\models\earl-street.glb --root /models/ --keepnames --printwidth 120 --precision 2 --draco true --preload --transform --resolution 4096
-->

<script module>
  import { T } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  const load = () => {
    return useGltf("/models/earl-street-transformed.glb", {
      dracoLoader: useDraco(),
    });
  };

  export const preload = async () => {
    await load();
  };
</script>

<script>
  let { fallback, error, children, ref = $bindable(), ...props } = $props();

  const gltf = load();
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Earl_Street"
      geometry={gltf.nodes.Earl_Street.geometry}
      material={gltf.materials["Lego Group"]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
