<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Projects\abc\static\models\f-toilet.glb --root /models/ --keepnames --printwidth 120 --precision 2 --draco true --preload --transform --resolution 4096
-->

<script context="module">
  import { T } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  const load = () => {
    return useGltf("/models/f-toilet-transformed.glb", {
      dracoLoader: useDraco(),
    });
  };

  export const preload = async () => {
    await load();
  };
</script>

<script>
  let { fallback, error, children, ref = $bindable(), ...props } = $props();

  const gltf = load();
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="FT-Set3" position={[18.2, -1.25, 11.09]}>
      <T.Mesh
        name="Plane006"
        geometry={gltf.nodes.Plane006.geometry}
        material={gltf.materials["TF-Backdrop"]}
      />
      <T.Mesh
        name="Plane006_1"
        geometry={gltf.nodes.Plane006_1.geometry}
        material={gltf.materials["TF-Floor"]}
      />
      <T.Mesh
        name="Plane006_2"
        geometry={gltf.nodes.Plane006_2.geometry}
        material={gltf.materials["TF-Backdrop"]}
      />
      <T.Mesh
        name="Plane006_3"
        geometry={gltf.nodes.Plane006_3.geometry}
        material={gltf.materials["TF-Backdrop"]}
      />
    </T.Group>
    <T.Group name="FT-Set1" position={[-2.91, 0.54, -4.09]}>
      <T.Mesh
        name="Cube040"
        geometry={gltf.nodes.Cube040.geometry}
        material={gltf.materials["Toilet Stall"]}
      />
      <T.Mesh
        name="Cube040_1"
        geometry={gltf.nodes.Cube040_1.geometry}
        material={gltf.materials["Toilet Stall"]}
      />
      <T.Mesh
        name="Cube040_2"
        geometry={gltf.nodes.Cube040_2.geometry}
        material={gltf.materials["Toilet Stall"]}
      />
      <T.Mesh
        name="Cube040_3"
        geometry={gltf.nodes.Cube040_3.geometry}
        material={gltf.materials["Toilet Stall"]}
      />
    </T.Group>
    <T.Group name="FT-Set2" position={[-4.56, 1.49, 0.64]}>
      <T.Mesh
        name="Cube044"
        geometry={gltf.nodes.Cube044.geometry}
        material={gltf.materials["Metal.002"]}
      />
      <T.Mesh
        name="Cube044_1"
        geometry={gltf.nodes.Cube044_1.geometry}
        material={gltf.materials["Quest.010"]}
      />
      <T.Mesh
        name="Cube044_2"
        geometry={gltf.nodes.Cube044_2.geometry}
        material={gltf.materials["Metal.002"]}
      />
      <T.Mesh
        name="Cube044_3"
        geometry={gltf.nodes.Cube044_3.geometry}
        material={gltf.materials["Metal.002"]}
      />
      <T.Group name="Microphone001" position={[4.02, -0.78, -0.26]}>
        <T.Mesh
          name="Cube049"
          geometry={gltf.nodes.Cube049.geometry}
          material={gltf.materials["Metal.002"]}
        />
        <T.Mesh
          name="Cube049_1"
          geometry={gltf.nodes.Cube049_1.geometry}
          material={gltf.materials["Metal.002"]}
        />
      </T.Group>
    </T.Group>
    <T.Group
      name="Guitar"
      position={[-3.95, -0.56, -1.58]}
      rotation={[0.02, -0.02, 0.02]}
    >
      <T.Mesh
        name="메쉬002"
        geometry={gltf.nodes.메쉬002.geometry}
        material={gltf.materials.Base}
      />
      <T.Mesh
        name="메쉬002_1"
        geometry={gltf.nodes.메쉬002_1.geometry}
        material={gltf.materials.Base}
      />
      <T.Mesh
        name="메쉬002_2"
        geometry={gltf.nodes.메쉬002_2.geometry}
        material={gltf.materials.Base}
      />
      <T.Mesh
        name="메쉬002_3"
        geometry={gltf.nodes.메쉬002_3.geometry}
        material={gltf.materials.Base}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
