<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 f-toilet-ktx-transformed.glb --root /models/transformed/ --keepnames --printwidth 120 --precision 2 --draco true --preload
-->

<script>
  import { T } from "@threlte/core";
  import { useGltf, useKtx2, useDraco, useCursor } from "@threlte/extras";

  const ktx2Loader = useKtx2("/transcoder/");
  const load = () => {
    return useGltf("/models/transformed/f-toilet-transformed.glb", {
      ktx2Loader: ktx2Loader,
      dracoLoader: useDraco(),
    });
  };

  export const preload = async () => {
    await load();
  };

  let { fallback, error, children, ref = $bindable(), ...props } = $props();
  import Hitbox from "./hitbox.svelte";

  const gltf = load();

  const { onPointerEnter, onPointerLeave } = useCursor();
</script>

<T.Group scale={1.4} bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="FT-Set3"
      geometry={gltf.nodes["FT-Set3"].geometry}
      material={gltf.materials["FT-Set3"]}
      position={[18.2, -1.25, 11.09]}
    />
    <T.Mesh
      name="FT-Set1"
      geometry={gltf.nodes["FT-Set1"].geometry}
      material={gltf.materials["FT-Set1"]}
      position={[-2.91, 0.54, -4.09]}
    />
    <T.Mesh
      name="FT-Set2"
      geometry={gltf.nodes["FT-Set2"].geometry}
      material={gltf.materials["FT-Set2"]}
      position={[-4.56, 1.49, 0.64]}
    />
    <T.Mesh
      name="Guitar"
      geometry={gltf.nodes.Guitar.geometry}
      material={gltf.materials.Guitar}
      position={[-3.95, -0.56, -1.58]}
      rotation={[0.02, -0.02, 0.02]}
      onpointerenter={onPointerEnter}
      onpointerleave={onPointerLeave}
      onclick={(e) => {
        e.stopPropagation();
        window.open("https://www.youtube.com/watch?v=_uEzKYpAo58", "_blank");
      }}
    >
      <Hitbox dim={[1, 2.8, 1.5]} position.y={0.5} />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
