<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 C:\Projects\abc\static\models\m-toilet.glb --root /models/ --keepnames --printwidth 120 --precision 2 --draco true --preload --transform --resolution 4096
-->

<script context="module">
  import { T } from "@threlte/core";
  import { useGltf, useDraco } from "@threlte/extras";

  const load = () => {
    return useGltf("/models/m-toilet-transformed.glb", {
      dracoLoader: useDraco(),
    });
  };

  export const preload = async () => {
    await load();
  };
</script>

<script>
  let { fallback, error, children, ref = $bindable(), ...props } = $props();

  const gltf = load();
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="MT-Set3" position={[-2.05, 0.62, -1.69]}>
      <T.Mesh
        name="Cube093"
        geometry={gltf.nodes.Cube093.geometry}
        material={gltf.materials["Procedural Grass"]}
      />
      <T.Mesh
        name="Cube093_1"
        geometry={gltf.nodes.Cube093_1.geometry}
        material={gltf.materials["Procedural Grass"]}
      />
      <T.Mesh
        name="Cube093_2"
        geometry={gltf.nodes.Cube093_2.geometry}
        material={gltf.materials["Procedural Grass"]}
      />
      <T.Mesh
        name="Cube093_3"
        geometry={gltf.nodes.Cube093_3.geometry}
        material={gltf.materials["Procedural Grass"]}
      />
      <T.Mesh
        name="Cube093_4"
        geometry={gltf.nodes.Cube093_4.geometry}
        material={gltf.materials["Procedural Grass"]}
      />
    </T.Group>
    <T.Group name="MT-Set1" position={[0.51, -0.38, -4.23]}>
      <T.Mesh
        name="Cube099"
        geometry={gltf.nodes.Cube099.geometry}
        material={gltf.materials["Bear Sign"]}
      />
      <T.Mesh
        name="Cube099_1"
        geometry={gltf.nodes.Cube099_1.geometry}
        material={gltf.materials["Bear Sign"]}
      />
      <T.Mesh
        name="Cube099_2"
        geometry={gltf.nodes.Cube099_2.geometry}
        material={gltf.materials["Bear Sign"]}
      >
        <T.MeshBasicMaterial
          map={gltf.materials["Bear Sign"].map}
          transparent={true}
          alphaTest={0.4}
        />
      </T.Mesh>
      <T.Mesh
        name="Cube099_3"
        geometry={gltf.nodes.Cube099_3.geometry}
        material={gltf.materials["Bear Sign"]}
      />
    </T.Group>
    <T.Group name="MT-Set4" position={[0.17, -0.76, 0.75]}>
      <T.Mesh
        name="Cylinder029"
        geometry={gltf.nodes.Cylinder029.geometry}
        material={gltf.materials["Wood.001"]}
      />
      <T.Mesh
        name="Cylinder029_1"
        geometry={gltf.nodes.Cylinder029_1.geometry}
        material={gltf.materials["Wood.001"]}
      />
      <T.Mesh
        name="Cylinder029_2"
        geometry={gltf.nodes.Cylinder029_2.geometry}
        material={gltf.materials["Wood.001"]}
      />
      <T.Mesh
        name="Cylinder029_3"
        geometry={gltf.nodes.Cylinder029_3.geometry}
        material={gltf.materials["Wood.001"]}
      />
      <T.Mesh name="Cylinder029_4" geometry={gltf.nodes.Cylinder029_4.geometry}>
        <T.MeshBasicMaterial
          map={gltf.materials["Wood.001"].map}
          transparent={true}
          alphaTest={0.4}
        />
      </T.Mesh>
      <T.Mesh
        name="Cylinder029_5"
        geometry={gltf.nodes.Cylinder029_5.geometry}
        material={gltf.materials["Wood.001"]}
      />
      <T.Mesh
        name="Cylinder029_6"
        geometry={gltf.nodes.Cylinder029_6.geometry}
        material={gltf.materials["Wood.001"]}
      />
      <T.Mesh
        name="Cylinder029_7"
        geometry={gltf.nodes.Cylinder029_7.geometry}
        material={gltf.materials["Wood.001"]}
      />
    </T.Group>
    <T.Group name="MT-Set2" position={[-2.38, 0.07, -3.22]}>
      <T.Mesh
        name="Cylinder028"
        geometry={gltf.nodes.Cylinder028.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_1"
        geometry={gltf.nodes.Cylinder028_1.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_2"
        geometry={gltf.nodes.Cylinder028_2.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_3"
        geometry={gltf.nodes.Cylinder028_3.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_4"
        geometry={gltf.nodes.Cylinder028_4.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_5"
        geometry={gltf.nodes.Cylinder028_5.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_6"
        geometry={gltf.nodes.Cylinder028_6.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_7"
        geometry={gltf.nodes.Cylinder028_7.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_8"
        geometry={gltf.nodes.Cylinder028_8.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_9"
        geometry={gltf.nodes.Cylinder028_9.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_10"
        geometry={gltf.nodes.Cylinder028_10.geometry}
        material={gltf.materials.DarkWood}
      />
      <T.Mesh
        name="Cylinder028_11"
        geometry={gltf.nodes.Cylinder028_11.geometry}
        material={gltf.materials.DarkWood}
      />
    </T.Group>
    <T.Group name="Maple_Tree" position={[0.37, 1.28, -3.97]}>
      <T.Mesh
        name="Cube100"
        geometry={gltf.nodes.Cube100.geometry}
        material={gltf.materials["MapleTree_Bark.001"]}
      />
      <T.Mesh
        name="Cube100_1"
        geometry={gltf.nodes.Cube100_1.geometry}
        material={gltf.materials["MapleTree_Bark.001"]}
      >
        <T.MeshBasicMaterial
          map={gltf.materials["MapleTree_Bark.001"].map}
          transparent={true}
          alphaTest={0.4}
        />
      </T.Mesh>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
