<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 m-toilet-ktx-transformed.glb --root /models/transformed/ --keepnames --printwidth 120 --precision 2 --draco true --preload
-->

<script>
  import { T } from "@threlte/core";
  import { useGltf, useKtx2, useDraco, useCursor } from "@threlte/extras";

  const ktx2Loader = useKtx2("/transcoder/");
  const load = () => {
    return useGltf("/models/ktx2/m-toilet-ktx.glb", {
      ktx2Loader: ktx2Loader,
      dracoLoader: useDraco(),
    });
  };

  export const preload = async () => {
    await load();
  };

  let { fallback, error, children, ref = $bindable(), ...props } = $props();
  import { getScene } from "$lib/stores/worldState.svelte.js";
  import { Tween } from "svelte/motion";
  import { cubicOut } from "svelte/easing";
  const scene = getScene();

  const { onPointerEnter, onPointerLeave } = useCursor();

  let signScale = new Tween([1, 1, 1], { duration: 175, easing: cubicOut });

  async function playTada() {
    await signScale.set([0.9, 0.9, 0.9]);
    await signScale.set([2, 2, 2]);
    await signScale.set([2, 2, 2]);
    await signScale.set([2, 2, 2]);
    await signScale.set([1, 1, 1]);
  }

  const gltf = load();
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="MT-Set3"
      geometry={gltf.nodes["MT-Set3"].geometry}
      material={gltf.materials["MT-Set3"]}
      position={[-2.05, 0.62, -1.69]}
    />
    <T.Mesh
      name="MT-Set1"
      geometry={gltf.nodes["MT-Set1"].geometry}
      position={[0.51, -0.38, -4.23]}
    >
      <T.MeshBasicMaterial map={gltf.materials["MT-Set1"].map} transparent={true} alphaTest={0.1} />
    </T.Mesh>
    <T.Mesh
      name="MT-Set4"
      geometry={gltf.nodes["MT-Set4"].geometry}
      material={gltf.materials["MT-Set4"]}
      position={[0.17, -0.76, 0.75]}
      onpointerenter={onPointerEnter}
      onpointerleave={onPointerLeave}
      onclick={(e) => {
        e.stopPropagation();
        window.open("https://www.youtube.com/watch?v=RgBwLQty8B4", "_blank");
      }}
    />
    <T.Mesh
      name="MT-Set2"
      geometry={gltf.nodes["MT-Set2"].geometry}
      material={gltf.materials["MT-Set2"]}
      position={[-2.38, 0.07, -3.22]}
    />
    <T.Mesh
      name="Maple_Tree"
      geometry={gltf.nodes.Maple_Tree.geometry}
      position={[0.37, 1.28, -3.97]}
    >
      <T.MeshBasicMaterial
        map={gltf.materials["Maple Tree"].map}
        transparent={true}
        alphaTest={0.4}
      />
    </T.Mesh>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
